[window]
opacity = 0.92
blur = true
padding = { x = 20, y = 20 }
decorations = "None"
dynamic_padding = true

[font]
size = 11.5 # 12 может быть крупноват для 1080p

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 1 # Важно для вертикальных отступов

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.15

[colors.primary]
background = "#1b1b1b" # Чуть мягче черного
foreground = "#e0e0e0"

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.cache/wal/colors-alacritty.toml" 
]
live_config_reload = true