[general]
# Импортируем динамические цвета Matugen
import = ["~/.cache/matugen/alacritty-colors.toml"]
live_config_reload = true

[window]
# Прозрачность для эффекта стекла
opacity = 0.7
padding = { x = 25, y = 25 }
decorations = "None"
dynamic_padding = true

[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 1

[cursor]
style = { shape = "Beam", blinking = "On" } # Тонкая линия (I-Beam) выглядит современнее
thickness = 0.15

[selection]
save_to_clipboard = true

[colors.primary]
# Это создаст темную подложку под текстом, даже если Matugen выдал светлые цвета
background = "#1a1b26" 
foreground = "#ffffff"