[colors.primary]
# background оставляем из surface, но foreground меняем на максимально контрастный
background = '{{colors.surface.default.hex}}'
foreground = '{{colors.on_surface_variant.default.hex}}' 

[colors.cursor]
# Курсор должен быть инвертированным для видимости
text = '{{colors.surface.default.hex}}'
cursor = '{{colors.primary.default.hex}}'

[colors.normal]
# Здесь важно, чтобы black не сливался с фоном, а white был действительно белым
black = '{{colors.surface_container_high.default.hex}}'
red = '{{colors.error.default.hex}}'
green = '{{colors.primary.default.hex}}'
yellow = '{{colors.tertiary.default.hex}}'
blue = '{{colors.secondary.default.hex}}'
magenta = '{{colors.primary_container.default.hex}}'
cyan = '{{colors.secondary_container.default.hex}}'
white = '{{colors.on_surface_variant.default.hex}}'

[colors.bright]
# Добавляем блок ярких цветов, чтобы системные сообщения (Bold) были еще четче
black = '{{colors.outline.default.hex}}'
red = '{{colors.error_container.default.hex}}'
green = '{{colors.primary.default.hex}}'
yellow = '{{colors.tertiary_container.default.hex}}'
blue = '{{colors.secondary_container.default.hex}}'
magenta = '{{colors.primary_container.default.hex}}'
cyan = '{{colors.secondary_container.default.hex}}'
white = '{{colors.on_surface.default.hex}}'