[config]
# Пустая секция config обязательна в новых версиях

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors-waybar.css'
output_path = '~/.cache/matugen/colors-waybar.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors-rofi.rasi'
output_path = '~/.cache/matugen/colors-rofi.rasi'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.cache/matugen/alacritty-colors.toml'

[templates.eww]
input_path = '~/.config/matugen/templates/eww-colors.scss'
output_path = '~/.cache/matugen/eww-colors.scss'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.cache/matugen/colors-hyprland.conf'

[templates.zen]
input_path = '~/.config/matugen/templates/zen-colors.css'
output_path = '~/.zen/kmknt1a6.Default (release)/chrome/zen-themes.css'

[templates.cosmic]
input_path = '~/.config/matugen/templates/cosmic-theme.ron'
output_path = '~/.config/cosmic/com.system76.CosmicTheme.User/v1/themes/Matugen-Crystal.ron'